fix(#32): fix starting app on MACos
VilnaCRM-Org/user-service pull request #33
Opened 2024-07-17 08:19 UTC by Derane

## Description
fix starting app on MACos

## Related Issue

https://github.com/VilnaCRM-Org/user-service/issues/32
## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [x] My code follows the code style of this project.
- [x] I have performed a self-review of my code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING.md**](https://github.com/VilnaCRM-Org/php-service-template/blob/main/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [x] All new and existing tests passed.
- [x] You have only one commit (if not, squash them into one commit).

2024-07-17 10:23 UTC, paaneko commented on infrastructure/docker/php/docker-entrypoint.sh
> +        rm -f var/test_acl_support
```suggestion
  chmod -R 755 var
```
WDYT?

2024-07-17 10:49 UTC, paaneko commented on infrastructure/docker/php/docker-entrypoint.sh
> +        rm -f var/test_acl_support
```suggestion
  if [ "$APP_ENV" = 'prod' ]; then
    setfacl -R -m u:www-data:rwX -m u:"$(whoami)":rwX var
    setfacl -dR -m u:www-data:rwX -m u:"$(whoami)":rwX var
  fi
```
OR this. That worked for me, too.

2024-07-17 11:09 UTC, Derane commented on infrastructure/docker/php/docker-entrypoint.sh
> +        rm -f var/test_acl_support
Looks good I will try this, thank you

2024-07-17 11:20 UTC, paaneko commented
I noticed I forgot to close the `if` tag with `fi`)

2024-07-17 11:21 UTC, paaneko commented on infrastructure/docker/php/docker-entrypoint.sh
> +    setfacl -dR -m u:www-data:rwX -m u:"$(whoami)":rwX var
```suggestion
    setfacl -dR -m u:www-data:rwX -m u:"$(whoami)":rwX var
  fi
```

2024-07-17 12:25 UTC, paaneko commented
Weirdly, on my mac everything runs good.

2024-07-17 21:59 UTC, Kravalg commented on infrastructure/docker/php/docker-entrypoint.sh
> +  chmod -R 755 var
Let's use setfacl if it's supported
In other cases we can use chmod

For example:
```
if command -v setfacl >/dev/null 2>&1; then
    # Check if ACLs are supported by trying to apply an ACL
    if setfacl -m u::rwx "$TARGET_DIR" 2>/dev/null; then
        echo "ACLs are supported. Setting ACLs..."
        setfacl -R -m u:www-data:rwX -m u:"$(whoami)":rwX "$TARGET_DIR"
    else
        echo "ACLs are not supported. Falling back to chmod..."
        chmod 755 -R "$TARGET_DIR"
    fi
else
    echo "setfacl command not found. Using chmod..."
    chmod 755 -R "$TARGET_DIR"
fi
```

2024-07-18 17:05 UTC, paaneko commented
2024-07-18 20:04:22 Waiting for db to be ready...
2024-07-18 20:04:22 The db is now ready and reachable
2024-07-18 20:04:22 
2024-07-18 20:04:22  [OK] Already at the latest version ("DoctrineMigrations\Version20240122085853")
2024-07-18 20:04:22 
2024-07-18 20:04:22 ACLs are supported. Setting ACLs...
2024-07-18 20:04:22 setfacl: var: Not supported

That my docker container logs.

2024-07-19 21:09 UTC, Kravalg requested changes

2024-07-19 21:09 UTC, Kravalg commented on .github/workflows/E2Etests-mac.yml
> +    runs-on: macos-13
Let’s try to use macOS 14

2024-07-22 22:55 UTC, Kravalg requested changes
Let’s fix the conflicts and then we will be able to merge this PR

2024-07-23 22:45 UTC, Kravalg approved these changes

2024-07-23 22:46 UTC, merged